import Head from 'next/head';

import Home from './home';

const Index = () => {
    return (
        <>
            <Head>
                <title>Aventus Dashboard</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Home />
        </>
    );
};

export default Index;
